import type { ColorPresetAdjustments } from "@/color-presets/application";

export type BuiltInColorPreset = {
	id: string;
	name: string;
	category: string;
	params: ColorPresetAdjustments;
	preview: [string, string, string];
	source: "built-in";
};

export const BUILT_IN_COLOR_PRESETS: BuiltInColorPreset[] = [
	{
		id: "clean-natural",
		name: "Clean Natural",
		category: "Natural",
		source: "built-in",
		params: {
			exposure: 0.08,
			contrast: 5,
			highlights: -8,
			shadows: 8,
			saturation: 1,
			vibrance: 8,
		},
		preview: ["#d8c6a9", "#829a83", "#40555a"],
	},
	{
		id: "bright-airy",
		name: "Bright & Airy",
		category: "Natural",
		source: "built-in",
		params: {
			exposure: 0.28,
			contrast: -8,
			highlights: -18,
			shadows: 22,
			temperature: 4,
			saturation: -5,
			vibrance: 8,
		},
		preview: ["#f7e9d2", "#c7dfe2", "#8da6a1"],
	},
	{
		id: "cinematic-teal",
		name: "Cinematic Teal",
		category: "Cinematic",
		source: "built-in",
		params: {
			exposure: -0.08,
			contrast: 22,
			highlights: -18,
			shadows: -8,
			temperature: -10,
			tint: -3,
			saturation: -8,
			vibrance: 14,
		},
		preview: ["#d98b55", "#315c64", "#172f3b"],
	},
	{
		id: "cinematic-warm",
		name: "Cinematic Warm",
		category: "Cinematic",
		source: "built-in",
		params: {
			contrast: 18,
			highlights: -14,
			shadows: 5,
			temperature: 15,
			tint: 3,
			saturation: -4,
			vibrance: 12,
		},
		preview: ["#dca16c", "#76513e", "#27373b"],
	},
	{
		id: "moody-film",
		name: "Moody Film",
		category: "Cinematic",
		source: "built-in",
		params: {
			exposure: -0.18,
			contrast: 28,
			highlights: -25,
			shadows: -15,
			temperature: 5,
			saturation: -18,
			vibrance: 7,
		},
		preview: ["#8d765e", "#53615b", "#242628"],
	},
	{
		id: "vintage-fade",
		name: "Vintage Fade",
		category: "Film",
		source: "built-in",
		params: {
			exposure: 0.05,
			contrast: -15,
			highlights: -18,
			shadows: 24,
			temperature: 12,
			tint: 4,
			saturation: -17,
		},
		preview: ["#d2a56f", "#8f886f", "#5c5b55"],
	},
	{
		id: "portra-soft",
		name: "Portra Soft",
		category: "Film",
		source: "built-in",
		params: {
			exposure: 0.12,
			contrast: -6,
			highlights: -20,
			shadows: 12,
			temperature: 8,
			tint: 5,
			saturation: -8,
			vibrance: 9,
		},
		preview: ["#e0b59d", "#a4aa91", "#6d7a72"],
	},
	{
		id: "golden-hour",
		name: "Golden Hour",
		category: "Warm",
		source: "built-in",
		params: {
			exposure: 0.14,
			contrast: 10,
			highlights: -10,
			shadows: 8,
			temperature: 25,
			tint: 4,
			saturation: 7,
			vibrance: 18,
		},
		preview: ["#ffbd58", "#cf704e", "#6c5541"],
	},
	{
		id: "cool-clean",
		name: "Cool Clean",
		category: "Cool",
		source: "built-in",
		params: {
			exposure: 0.08,
			contrast: 9,
			highlights: -12,
			shadows: 10,
			temperature: -18,
			tint: 2,
			saturation: -4,
			vibrance: 11,
		},
		preview: ["#c8e1e8", "#668d9c", "#314b61"],
	},
	{
		id: "vivid-pop",
		name: "Vivid Pop",
		category: "Creative",
		source: "built-in",
		params: {
			contrast: 16,
			highlights: -8,
			shadows: 6,
			saturation: 14,
			vibrance: 30,
		},
		preview: ["#ff6b58", "#ffd34e", "#27a59f"],
	},
	{
		id: "soft-pastel",
		name: "Soft Pastel",
		category: "Creative",
		source: "built-in",
		params: {
			exposure: 0.18,
			contrast: -18,
			highlights: -16,
			shadows: 20,
			temperature: 3,
			saturation: -13,
			vibrance: 8,
		},
		preview: ["#eac1ca", "#b9d7d1", "#b3b2d7"],
	},
	{
		id: "mono-contrast",
		name: "Mono Contrast",
		category: "B&W",
		source: "built-in",
		params: {
			contrast: 30,
			highlights: -12,
			shadows: -18,
			saturation: -100,
			vibrance: -100,
		},
		preview: ["#d8d8d8", "#777777", "#202020"],
	},
];
